AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: index.handler
      Runtime: nodejs18.x
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
            Auth:
              Authorizer: NONE
        HelloWorldPost:
          Type: Api
          Properties:
            Path: /hello
            Method: post
            Auth:
              Authorizer: NONE