AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

# Deployment Configuration
Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    Environment:
      Variables:
        STAGE: !Ref AWS::StackName

# Parameters for deployment customization
Parameters:
  Environment:
    Type: String
    Default: dev
    Description: Environment name (dev, staging, prod)
    AllowedValues:
      - dev
      - staging
      - prod

Resources:
  # DynamoDB Table
  HelloWorldTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-hello-world-table"
      AttributeDefinitions:
        - AttributeName: name
          AttributeType: S
      KeySchema:
        - AttributeName: name
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: index.handler
      Runtime: nodejs18.x
      FunctionName: !Sub "${AWS::StackName}-hello-world"
      Description: "Hello World Lambda Function with DynamoDB"
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          FUNCTION_NAME: !Ref AWS::StackName
          TABLE_NAME: !Ref HelloWorldTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref HelloWorldTable
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
            RestApiId: !Ref HelloWorldApi
        HelloWorldPost:
          Type: Api
          Properties:
            Path: /hello
            Method: post
            RestApiId: !Ref HelloWorldApi

  # API Gateway
  HelloWorldApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment
      Description: "API Gateway for Hello World Lambda"
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

# Outputs for deployment
Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Hello World function"
    Value: !Sub "https://${HelloWorldApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/hello/"
    Export:
      Name: !Sub "${AWS::StackName}-ApiUrl"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-FunctionArn"
  HelloWorldTable:
    Description: "DynamoDB Table Name"
    Value: !Ref HelloWorldTable
    Export:
      Name: !Sub "${AWS::StackName}-TableName"
  StackName:
    Description: "Name of the CloudFormation stack"
    Value: !Ref AWS::StackName
    Export:
      Name: !Sub "${AWS::StackName}-StackName"